<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>InstaladorNewAcesso.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InstaladorNewAcesso.Abstractions\InstaladorNewAcesso.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>InstaladorNewAcesso.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
