<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>InstaladorNewAcesso.Console</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InstaladorNewAcesso.Abstractions\InstaladorNewAcesso.Abstractions.csproj" />
    <ProjectReference Include="..\InstaladorNewAcesso.Core\InstaladorNewAcesso.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

</Project>
